### ISSUE TITLE
Reproduction Study To-do List

### ISSUE THREAD

**Issue by Liam-W-Smith** [HEGSRR/RPl-Spielman-2020#1]
To do:
- [x] Double check i did the environment stuff as Bell and Joe wanted
- [x] Create PDF and register reproduction report
- [x] Create poster
- [x] Read papers
- [x] Reproduction report: add discussion section
- [x] figure display
- [x] fix figure 1
- [x] Include instructions for recovering my environment?
- [x] why didn't we use pandas to write our csv figures?
- [x] where 2 store metadata generating file
- [x] try seeing if within 0.1 or 1 eliminates extra check to o
- [x] round #s in table
- [x] sovi inputs thing
- [x] Delete package versions in code? Refer people to requirements.txt?
- [x] Delete anything that says we are using a containerized conda environment -- figure out the wording for pip version
- [x] Reproduction report: save figures
- [x] move all irrelevant code out
- [x] Update results metadata file
- [x] Delete unnecessary files
- [x] Reproduction report: add conclusions section
- [x] Reproduction report: add references section
- [x] Get the conda environment finished and yml file complete
- [x] Reproduction report: clean up comments on vars -- maybe double check how they're calculating their vars first
- [x] Possibly write to David Folch to ask why our results might be different
- [x] relabel original as national model, get rid of expected column
- [x] Documentation: add a complete metadata file for each of my data sources (missing spielman shapefile still)
- [x] Documentation: update data metadata csv
- [x] Documentation: replace variable names RDS file with markdown from reproduction report
- [x] Reproduction report: add in unplanned deviations in bold (as it makes sense within pre-existing document)
- [x] Reproduce all outputs, fix differences
- [x] Make one master Jupyter notebook to hold the reproduction report
- [x] check results against Spielman's -- do I have all the necessary results? do a robust equivalency test
- [x] re-read paper and identify ALL OUTPUTS to confirm which ones actually needed in the code (CA map, table 2, figure 2)
- [x] functions for exporting table from python into markdown?
- [x] pull data dictionary from census into python
- [x] Finish filling in metadata information and methodology in analysis plan, then split to have analysis plan and reproduction report. 
- [x] Create scratch code and actual code folders, test to make sure it runs
- [x] Create version 1 derived data folders
- [x] Finish workflows 
- [x] Finish theoretical consistency workflow and code
- [x] delete all extraneous code, store copies of the completed code though
- [x] get visualization script to run
- [x] compute eigenvalues before varimax rotation? check both the python and R packages and look for documentation
- [x] fix deprecation warning
- [x] Keep looking for potential use of decennial vars... no use
- [x] Determine whether calculating standard error and the equivalency tests and dec data useful for anything - no use
- [x] Impute for NaN in MHSEVAL_ALT
- [x] Save data
- [x] Get compute_sovi.ipynb to run
- [x] check for zeros
- [x] descriptive stats for all the variables (any 0s?)
- [x] Try learning a new package for PCA
- [x] double check no missing data right before pca
- [x] create data dictionary for census metadata
- [x] make "spielman" data for all spielman data in raw public
- [x] fill in data directory table
- [x] check what results they provide
- [x] SoVI results are looking different between my data and theirs -- try their data under my analysis and see if issue persists. There are slight differences between the variable derived from land area, so maybe it's just very susceptible to small pertubations in values. UPDATE: I had rounded the area values to the nearest integer for comparison purposes in my new data. I was calculating SoVI on my rounded data and Spielman's unrounded data. Having recalculated SoVI on unrounded data, my results match now! But I need to update the retrieving census data to show that I did that check and also leave it unrounded at the end of the script.
- [x] There is potentially an issue in their function. Might need to iron it out line by line implementing their function
- [x] Check that pandas.Series.quantile is the same as pysal.Quantiles
- [x] How do I find documentation for old pysal functions? .yb issue with quantiles
- [x] Fill in top-level readme
- [x] Add color for study metadata to Zotero

Questions:
- [x] How is it possible to be an island but not be missing spatial lag?

**Comment by josephholler** [comment]
Registration process started on OSF!
