### ISSUE TITLE
Replication Study To-Do List

### ISSUE THREAD

**Issue by josephholler** [HEGSRR/RPl-Spielman-2020#5]
- [x] Double check that we are calculating SoVI input variables in a reasonable manner. Examples: counties['QRICH200K'] = (counties.B19001_017E) / counties.B11001_001E # would B19001_001E be a better denominator? counties['PERCAP_ALT'] = counties.B19025_001E / (counties.B25008_001E) # is there a better source of per capita income?
- [x] Add methodology to analysis plan
- [x] Planned deviations and method for evaluating success of replication.
- [x] Think about joining as much output data as possible into one table to facilitate eventual comparison of results
- [x] This python notebook may provide some good examples of analyzing change over time:
https://www.kaggle.com/code/prashant111/complete-guide-on-time-series-analysis-in-python
- [x] Determine temporal extent of ACS data available for temporal replication
- [x] Would the model be more stable if components were weighted by their eigenvalue? Include method to test this in analysis plan
- [x] Preregister analysis plan prior to downloading data

**Comment by josephholler** [comment]
saving eigenvalue idea for later and closing this issue upon registering the preanalysis plan
